name: mnklibrary build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build -c Release --no-restore
    - name: Run tests
      run: dotnet test -c Release --no-restore --no-build
    - name: Create nuget packages
      run: dotnet pack -c Release